//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RacemapEntities : DbContext
    {
        public RacemapEntities()
            : base("name=RacemapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AhotuRace> AhotuRaces { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<ChildRace> ChildRaces { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<RaceSeria> RaceSerias { get; set; }
        public virtual DbSet<RaceTag> RaceTags { get; set; }
        public virtual DbSet<RaceType> RaceTypes { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
