//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class racemapEntities : DbContext
    {
        public racemapEntities()
            : base("name=racemapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Race> Races { get; set; }
        public DbSet<RaceDistance> RaceDistances { get; set; }
        public DbSet<RaceHistory> RaceHistories { get; set; }
        public DbSet<RaceStage> RaceStages { get; set; }
    }
}
