//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string Place { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public string CategoryFull { get; set; }
        public string Url { get; set; }
        public string Tags { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RaceId { get; set; }
        public Nullable<System.Guid> TypeId { get; set; }
    }
}
