//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceDistance
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string Track { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.Guid> RaceId { get; set; }
    }
}
